#
###################################
# Site wide configuration
####################################
#
title: Dankas
email:
description: A simple and awesome blog theme powered by jekyll.
url: # the base hostname & protocol for your site
keywords: ["blog", "jekyll"]

#
###################################
# Jekyll configuration
####################################
#
timezone:          america/Montevideo
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Dankas
  avatar: cilonio.gif
  job: "Eu faço coisas!"
  bio: "01001000 01100101 01101100 01101100 01101111 00100000 00111011 00101001"
  email: 
  disqus-shortname: dankasmoraes
  twitter: dankas__
  facebook: dankasmoraes
  google:
    plus: #username
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: dankas
  gitlab: #username
  stackoverflow: 156327/daniel-moraes
  linkedin: dankasmoraes
  skype: #username
  xing: #username
  instagram: dankas__
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  500px: #username
  codepen: #username
  reddit: #username
  telegram: #username
