title: 0XC3!
subtitle: 01001000 01100101 01101100 01101100 01101111 00100000 00111011 00101001
description: >- # this means to ignore newlines until "baseurl:"
  A Jekyll Theme Built For Developers
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://dankas.github.io" # the base hostname & protocol for your site, e.g. http://example.com

author_logo: profile.png
disqus_shortname: dankasmoraes  #for comments using disqus
author: devlopr
author_bio: devlopr-jekyll is a theme built for developers. Anyone can create a blog like this. As easy as PIE !
author_email: "dankasmoraes@gmail.com"
author_location: Pelotas
author_website_url: "https://sujaykundu.com"

# social links
twitter_username: dankas__
github_username:  dankas
facebook_username: dankasmoraes
linkedin_username: dankasmoraes
behance_username: 
instagram_username: dankas__
medium_username: 
telegram_username: 
dribbble_username: 
flickr_username: 

# dont touch this unless required
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  #- jekyll-analytics
  - jekyll-algolia
  - jekyll-menus 


# code highlighter
highlighter: rouge



# minify html
compress_html:
    clippings: []
    comments: []
    endings: []
    ignore:
    envs: []
    blanklines: false
    profile: false
    startings: []

# algolia search 
algolia:
  application_id: D9WA1YKTRQ
  index_name: blog_posts # You can replace that with whatever name you want
  files_to_exclude: []
  nodes_to_index: 'article'
  search_only_api_key: 58ffdd7cd6c45ec1577a7fcd789b1b9a
