#
###################################
# Site wide configuration
####################################
#
title: Dankas
email: dankasmoraes@gmail.com
description: Blog pessoal sobre programação e engenharia.
url: # the base hostname & protocol for your site
keywords: ["blog", "jekyll"]

#
###################################
# Jekyll configuration
####################################
#
timezone:          america/Montevideo
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Dankas
  avatar: cilonio.gif
  job: "Eu faço coisas!"
  bio: "01001000 01100101 01101100 01101100 01101111 00100000 00111011 00101001"
  email: 
  disqus-shortname: dankas
  twitter: dankas__
  facebook: dankasmoraes
  google:
    plus: #username
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: dankas
  gitlab: #username
  stackoverflow: 10302105/daniel-moraes
  linkedin: dankasmoraes
  skype: #username
  xing: #username
  instagram: dankas__
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: UCDcSZl7JbE_f8WqLBMH0ndg
  soundcloud: #username
  weibo: #username
  flickr: #username
  500px: #username
  codepen: #username
  reddit: #username
  telegram: #username
